# Generated by Django 5.1.3 on 2024-11-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='access',
            field=models.CharField(choices=[('any', 'AnyOne'), ('email', 'Email Required')], default='email', max_length=14),
        ),
    ]
